# Generated by Django 3.0.4 on 2020-06-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category2',
            field=models.CharField(default='no category', max_length=30),
        ),
    ]
