# Generated by Django 3.0.4 on 2020-06-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=100)),
                ('address2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=70)),
                ('state', models.CharField(default='', max_length=70)),
                ('zip_code', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
