# Generated by Django 3.0.4 on 2020-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
