# Generated by Django 3.0.4 on 2020-06-26 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(default=datetime.date(2020, 6, 26)),
        ),
    ]
