# Generated by Django 3.0.4 on 2020-06-26 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200626_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2020, 6, 26, 5, 27, 58, 316473, tzinfo=utc)),
        ),
    ]
