# Generated by Django 3.0.4 on 2020-06-27 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200626_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2020, 6, 27, 6, 9, 57, 347270, tzinfo=utc)),
        ),
    ]
