# Generated by Django 3.0.4 on 2020-06-27 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200627_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2020, 6, 27, 14, 37, 29, 896598, tzinfo=utc)),
        ),
    ]
